name: "[mainnet-deploy] deploy staker"

on:
  workflow_dispatch:
    inputs:
      stakeTokenAddress:
        description: 'Stake Token Address'
        required: true
        type: string
      paymentTokenAddress:
        description: 'Payment Token Address'
        required: true
        type: string
      adminAddress:
        description: 'Admin Address'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: mainnet
      url: https://term-finance.github.io/term-finance-staker/
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Foundry
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        foundryup

    - name: Deploy contract
      env:
        RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        STAKE_TOKEN_ADDRESS: ${{ github.event.inputs.stakeTokenAddress }}
        PAYMENT_TOKEN_ADDRESS: ${{ github.event.inputs.paymentTokenAddress }}
        ADMIN: ${{ github.event.inputs.adminAddress }}
      run: |
        forge script script/Deploy.s.sol:Deploy --rpc-url $RPC_URL --private-key $PRIVATE_KEY 