name: "[mainnet-deploy] deploy staker"

on:
  workflow_dispatch:
    inputs:
      stakeTokenAddress:
        description: 'Stake Token Address'
        required: true
        type: string
      payoutTokenAddress:
        description: 'Payout Token Address'
        required: true
        type: string
      adminAddress:
        description: 'Admin Address'
        required: true
        type: string
      rewardNotifier:
        description: 'Reward Notifier Address'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: mainnet
      url: https://term-finance.github.io/term-finance-staker/
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge install
      - run: forge build
      - run: forge tree
      - name: Deploy contract
        env:
          RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          STAKE_TOKEN_ADDRESS: ${{ github.event.inputs.stakeTokenAddress }}
          PAYOUT_TOKEN_ADDRESS: ${{ github.event.inputs.payoutTokenAddress }}
          ADMIN: ${{ github.event.inputs.adminAddress }}
          REWARD_NOTIFIER: ${{ github.event.inputs.rewardNotifier }}
        run: |
          forge script script/Deploy.s.sol:Deploy --rpc-url $RPC_URL --private-key $PRIVATE_KEY --broadcast --verify